---
title: "Untitled"
author: "frank"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(scales)
#library(Smisc)
library(timetk)
library(magrittr)
library(dplyr)
library(xtable)
library(rbokeh)
library(magrittr)
source("funciones.R")
library(extrafont)
loadfonts()
library(ggpointdensity)
library(ggprism)
library(lubridate)
library(timetk)
## Including Plots
```
MANO IZQ

```{r pressure, echo=FALSE}
df1 = read.csv("../../Phd-actigraphy/examples/DA:AF:D8:D4:D8:D7-12-06-2022-20-24-04-m-izq/acceleration-12-06-2022-20-24-05.csv",header = F)
df1 = df1[3:length(df1$V1),]
df1 %<>% mutate(time =as.POSIXct(V1))
df1 %<>% mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df1 = df1[df1$V1 >= "19:50:00" & df1$V1 <= "20:10:00",]

df2 = read.csv("../../Phd-actigraphy/examples/DA:AF:D8:D4:D8:D7-12-06-2022-20-24-04-m-izq/angular-velocity-12-06-2022-20-24-05.csv",header = F)
df2 = df2[3:length(df2$V1),]
df2 %<>% mutate(time =as.POSIXct(V1))
df2 %<>% mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df2 = df18[df2$V1 >= "19:50:00" & df2$V1 <= "20:10:00",]

#df3 = read.csv("../../Phd-actigraphy/examples/DA:AF:D8:D4:D8:D7-12-06-2022-20-24-04-m-izq/illuminance-12-06-2022-20-24-05.csv",header = F)
#df4 = read.csv("../../Phd-actigraphy/examples/DA:AF:D8:D4:D8:D7-12-06-2022-20-24-04-m-izq/magnetic-field-12-06-2022-20-24-05.csv",header = F)
df5 = read.csv("../../Phd-actigraphy/examples/DA:AF:D8:D4:D8:D7-12-06-2022-20-24-04-m-izq/temperature[1]-12-06-2022-20-24-05.csv",header = F)
df5 = df5[3:length(df5$V1),]
df5 %<>% mutate(time =as.POSIXct(V1))
df5 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df5 = df5[df5$V1 >= "19:50:00" & df5$V1 <= "20:10:00",]

```

MANO DER
```{r}
df6 = read.csv("../../Phd-actigraphy/examples/D6:CE:7B:B9:21:B2-12-06-2022-20-19-27-m-drc/acceleration-12-06-2022-20-19-28.csv",header = F)
df6 = df6[3:length(df6$V1),]
df6 %<>% mutate(time =as.POSIXct(V1))
df6 %<>% mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df6 = df6[df6$V1 >= "19:50:00" & df6$V1 <= "20:10:00",]

df7 = read.csv("../../Phd-actigraphy/examples/D6:CE:7B:B9:21:B2-12-06-2022-20-19-27-m-drc/angular-velocity-12-06-2022-20-19-28.csv",header = F)
df7 = df7[3:length(df7$V1),]
df7 %<>% mutate(time =as.POSIXct(V1))
df7 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df7 = df18[df7$V1 >= "19:50:00" & df7$V1 <= "20:10:00",]

df8 = read.csv("../../Phd-actigraphy/examples/D6:CE:7B:B9:21:B2-12-06-2022-20-19-27-m-drc/temperature[1]-12-06-2022-20-19-28.csv",header = F)
df8 = df8[3:length(df8$V1),]
df8 %<>% mutate(time =as.POSIXct(V1))
df8 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df8 = df8[df8$V1 >= "19:50:00" & df8$V1 <= "20:10:00",]

```

```{r}
df9 = read.csv("../../Phd-actigraphy/examples/D0:06:F7:7C:91:AE-12-06-2022-20-46-14-t-izq/acceleration-12-06-2022-20-46-15.csv",header = F)
df9 = df9[3:length(df9$V1),]
df9 %<>% mutate(time =as.POSIXct(V1))
df9 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df9 = df9[df9$V1 >= "19:50:00" & df9$V1 <= "20:10:00",]


df10 = read.csv("../../Phd-actigraphy/examples/D0:06:F7:7C:91:AE-12-06-2022-20-46-14-t-izq/angular-velocity-12-06-2022-20-46-15.csv",header = F)
df10 = df10[3:length(df10$V1),]
df10 %<>% mutate(time =as.POSIXct(V1))
df10 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df10 = df10[df10$V1 >= "19:50:00" & df10$V1 <= "20:10:00",]


#df11 = read.csv("../../Phd-actigraphy/examples/D0:06:F7:7C:91:AE-12-06-2022-20-46-14-t-izq/illuminance-12-06-2022-20-46-15.csv",header = F)
#df12 = read.csv("../../Phd-actigraphy/examples/D0:06:F7:7C:91:AE-12-06-2022-20-46-14-t-izq/magnetic-field-12-06-2022-20-46-15.csv",header = F)
df13 = read.csv("../../Phd-actigraphy/examples/D0:06:F7:7C:91:AE-12-06-2022-20-46-14-t-izq/temperature[1]-12-06-2022-20-46-15.csv",header = F)
df13 = df13[3:length(df13$V1),]
df13 %<>% mutate(time =as.POSIXct(V1))
df13 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df13 = df13[df13$V1 >= "19:50:00" & df13$V1 <= "20:10:00",]

```

```{r}
df14 = read.csv("../../Phd-actigraphy/examples/D5:84:46:FE:E5:14-12-06-2022-20-38-50-t-drc/acceleration-12-06-2022-20-38-51.csv",header = F)
df14 = df14[3:length(df14$V1),]
df14 %<>% mutate(time =as.POSIXct(V1))
df14 %<>% mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df14 = df14[df14$V1 >= "19:50:00" & df14$V1 <= "20:10:00",]


df15 = read.csv("../../Phd-actigraphy/examples/D5:84:46:FE:E5:14-12-06-2022-20-38-50-t-drc/angular-velocity-12-06-2022-20-38-51.csv",header = F)
df15 = df15[3:length(df15$V1),]
df15 %<>% mutate(time =as.POSIXct(V1))
df15 %<>%  mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df15 = df15[df15$V1 >= "19:50:00" & df15$V1 <= "20:10:00",]

#df16 = read.csv("../../Phd-actigraphy/examples/D5:84:46:FE:E5:14-12-06-2022-20-38-50-t-drc/illuminance-12-06-2022-20-38-51.csv",header = F)
#df17 = read.csv("../../Phd-actigraphy/examples/D5:84:46:FE:E5:14-12-06-2022-20-38-50-t-drc/magnetic-field-12-06-2022-20-38-51.csv",header = F)
df18 = read.csv("../../Phd-actigraphy/examples/D5:84:46:FE:E5:14-12-06-2022-20-38-50-t-drc/temperature[1]-12-06-2022-20-38-51.csv",header = F)
df18 = df18[3:length(df18$V1),]
df18 %<>% mutate(time =as.POSIXct(V1))
df18 %<>% mutate(V1 = format(as.POSIXct(V1),"%H:%M:%S"))
df18 = df18[df18$V1 >= "19:50:00" & df18$V1 <= "20:10:00",]

```


```{r}
df1 %<>%mutate(V2 = as.numeric(gsub(".*:","",V2)),V3 = as.numeric(gsub(".*:","",V3)), V4 = as.numeric(gsub(".*:","",V4)))
df1 %<>% mutate(extremidad = "M.izq")
df6 %<>%mutate(V2 = as.numeric(gsub(".*:","",V2)),V3 = as.numeric(gsub(".*:","",V3)), V4 = as.numeric(gsub(".*:","",V4)))
df6 %<>% mutate(extremidad = "M.der")
df9 %<>%mutate(V2 = as.numeric(gsub(".*:","",V2)),V3 = as.numeric(gsub(".*:","",V3)), V4 = as.numeric(gsub(".*:","",V4)))
df9 %<>% mutate(extremidad = "P.izq")
df14 %<>%mutate(V2 = as.numeric(gsub(".*:","",V2)),V3 = as.numeric(gsub(".*:","",V3)), V4 = as.numeric(gsub(".*:","",V4)))
df14 %<>% mutate(extremidad = "P.der")

```
```{r}
dfN <- rbind(df1, df6,df9,df14)

```


```{r}
dfN %>% ggplot(aes(x = time, y = V2, shape =extremidad, color = extremidad)) +
  geom_line(aes(group = 1)) +
  facet_wrap(~extremidad,ncol = 1,scales="free_x") + 
  xlab("Hora") + 
  ylab("g") +
  theme_prism(border = F,base_size = 10, base_line_size = 0.6,palette = "stained_glass") + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, size = 9),
        axis.text.y = element_text(angle = 0, vjust = 0.5, size = 9),
        axis.title=element_text(size=14,face="bold"),
        legend.text=element_text(size=12),
        legend.position = "bottom")+
  scale_y_continuous(breaks = seq(min(dfN$V2), max(dfN$V2), by = .4))+
  scale_x_datetime(date_breaks = "2 min", labels = date_format("%H:%M:%S"))+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 19:50:00")), colour = "red",size=1)+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 19:54:40")), colour = "red",size=1)+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 19:55:00")), colour = "lightblue",size=1)+
    geom_vline(aes(xintercept = as.POSIXct("2022-12-06 19:57:20")), colour = "lightblue",size=1)+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 19:57:30")), colour = "green",size=1)+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 19:59:00")), colour = "green",size=1)+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 20:00:00")), colour = "yellow",size=1)+
  geom_vline(aes(xintercept = as.POSIXct("2022-12-06 20:04:00")), colour = "yellow",size=1)#+
  #geom_rect(aes(xmin=as.POSIXct("2022-12-06 20:00:00"), xmax=as.POSIXct("2022-12-06 20:04:00"),color=NA , ymin=-Inf,ymax=Inf), alpha=0,fill="yellow")







ggsave("../../Phd-actigraphy/acel.pdf",width = 18,height =12 )

  
```



```{r}
dfg = read.csv("../Phd-actigraphy/FrankB_glucose_23-11-2022.csv",header = F)
dfg = dfg[3:length(dfg$V1),]
dfg %<>% select(V3,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14)
dfg %<>% mutate(time =  strptime(V3, format="%d-%m-%Y %H:%M", tz = "UTC"))
dfg %<>% arrange(time)
dfg <-dfg %>% filter(time> as.POSIXct("2022-11-21 00:00:00"))
```

```{r}
dfg$day <- format(as.Date(dfg$time,format="%Y-%m-%d"), format = "%d")
dfg %<>% filter(day %in% c(21,22,23))
dfg$V5 <- as.numeric(dfg$V5,na.rm=T)
dfg %<>% select(-V3)
```

```{r}
dfg %<>% filter(!is.na(V5))
```

```{r}
dfg %<>% select(time,V5,day)
```

```{r}
dfg %<>% mutate(time = as.POSIXct(time))
```


```{r}
dfg %>% ggplot(aes(x = time, y = V5, shape =day, color =day)) +
  geom_line(aes(group = 1)) +
  facet_wrap(~day,ncol = 1,scales="free_x") + 
  xlab("Día") + 
  ylab("Glucosa(mg/dL)") +
  theme_prism(border = F,base_size = 10, base_line_size = 0.6,palette = "stained_glass") + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, size = 9),
        axis.text.y = element_text(angle = 0, vjust = 0.5, size = 9),
        axis.title=element_text(size=14,face="bold"),
        legend.text=element_text(size=12),
        legend.position = "bottom")+
  scale_y_continuous(breaks = seq(min(dfg$V5,na.rm = T), max(dfg$V5,na.rm = T), by = 10))+
  scale_x_datetime(date_breaks = "1 hour", labels = date_format("%H:%M"))
ggsave("../../Phd-actigraphy/glucosa.pdf",width = 18,height =12 )

```

