---
title: "R Notebook"
output: html_notebook
---

```{r echo=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(scales)
library(timetk)
library(magrittr)
library(dplyr)
library(xtable)
library(rbokeh)
library(magrittr)
#source("funciones.R")
library(extrafont)
loadfonts()
library(ggpointdensity)
library(ggprism)
library(lubridate)
library(timetk)
```

```{r}
dfg = read.csv("FrankB_glucose_24-1-2023.csv",header = F)
dfg = dfg[3:length(dfg$V1),]
dfg %<>% select(V3,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14)
dfg %<>% mutate(time =  strptime(V3, format="%d-%m-%Y %H:%M", tz = "UTC"))
dfg %<>% arrange(time)

dfg <- dfg %>% mutate(V5 = ifelse(V5 %in% "", V6, V5))
dfg <- dfg %>% select(-V6,-V7,-V8,-V9,-V10,-V11,-V12,-V13,-V3) 
dfg$day <- format(as.Date(dfg$time,format="%Y-%m-%d"), format = "%d")
dfg %<>% filter(day %in% c(25,27,28,29,30))

dfg_labels <- dfg %>% dplyr::filter(V14!="") %>% select(-V5)
dfg_labels %<>% mutate(time = as.POSIXct(time),V14 = as.factor(V14)) %>% mutate(val = 190) %>% rename(label=V14)
dfg_labels %<>% select(time,val, label,day)

dfg <- dfg  %>% dplyr::filter(V5!="")

dfg$V5 <- as.numeric(dfg$V5,na.rm=T)
dfg %<>% select(time,V5,day)
dfg %<>% mutate(time = as.POSIXct(time))
```


```{r}
for(i in 1:length(dfg_labels$val)){
  if((i %% 2) == 0) {
  dfg_labels$val[i]<-dfg_labels$val[i]+10
  }else{
    dfg_labels$val[i]<-dfg_labels$val[i]-10
  }
}
```


```{r}
p<- dfg %>% ggplot(aes(x = time, y = V5, shape =day, color =day)) +
  geom_line(aes(group = 1)) +
  facet_wrap(~day,ncol = 2,scales="free_x") + 
  xlab("Día") + 
  ylab("Glucosa(mg/dL)") +
  theme_prism(border = F,base_size = 10, base_line_size = 0.6,palette = "stained_glass") + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, size = 9),
        axis.text.y = element_text(angle = 0, vjust = 0.5, size = 9),
        axis.title=element_text(size=14,face="bold"),
        legend.text=element_text(size=12),
        legend.position = "bottom")+
  scale_y_continuous(breaks = seq(min(dfg$V5,na.rm = T), max(dfg$V5,na.rm = T), by = 10))+
  scale_x_datetime(date_breaks = "1 hour", labels = date_format("%H:%M:%S"))
#ggsave("../../Phd-actigraphy/glucosa.pdf",width = 18,height =12 )

```

```{r echo=FALSE}
library(ggrepel)
p<-p+geom_vline(data =dfg_labels, aes(xintercept = time),  linetype = 1, colour = "red")
p+  geom_text(data = dfg_labels, aes( x=time, y=val, label=label),color="green", size=3)
#p+  geom_label(data = dfg_labels, aes( x=time, y=val, label=label),color="green",  fontface = "bold",size=3)
ggsave("images//glucosa.pdf",width = 18,height =7 )

```
